# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: binder
spec:
  selector:
    app: binder
  ports:
    - name: webhook
      protocol: TCP
      port: 443
      targetPort: {{ .Values.binder.ports.webhookPort }}
    - name: http-metrics
      protocol: TCP
      port: {{ .Values.binder.ports.metricsPort }}
      targetPort: {{ .Values.binder.ports.metricsPort }}
  sessionAffinity: None
  type: ClusterIP