# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: binder
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: binder
  template:
    metadata:
      labels:
        app: binder
    spec:
      serviceAccountName: binder
      containers:
        - name: binder
          image: "{{ .Values.global.registry }}/{{ .Values.binder.image.name }}:{{ .Chart.Version }}"
          imagePullPolicy: {{ .Values.binder.image.pullPolicy }}
          args:
            - "--leader-elect={{ .Values.global.leaderElection }}"
            - "--health-probe-bind-address=:{{ .Values.binder.ports.probePort }}"
            - "--resource-reservation-pod-image={{ .Values.global.registry }}/{{ .Values.binder.resourceReservationImage.name }}:{{ .Chart.Version }}"
            - "--metrics-bind-address=:{{ .Values.binder.ports.metricsPort }}"
            - "--cdi-enabled={{ .Values.binder.cdi }}"
            - "--resource-reservation-namespace={{ .Values.global.resourceReservation.namespace }}"
            - "--resource-reservation-service-account={{ .Values.global.resourceReservation.serviceAccount }}"
            - "--resource-reservation-app-label={{ .Values.global.resourceReservation.appLabel }}"
          {{- if .Values.binder.additionalArgs }}
            {{- toYaml .Values.binder.additionalArgs | nindent 12 }}
          {{- end }}
          {{- if .Values.binder.resources }}
          resources:
            {{- toYaml .Values.binder.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.global.securityContext }}
          securityContext:
            {{- toYaml .Values.global.securityContext | nindent 12 }}
          {{- end }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.global.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.global.affinity }}
      affinity:
        {{- toYaml .Values.global.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.global.tolerations }}
      tolerations:
        {{- toYaml .Values.global.tolerations | nindent 8 }}
      {{- end }}
