# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kai-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app: kai-operator
