# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.global.clusterAutoscaling }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.nodescaleadjuster.scalingPodNamespace }}
{{- end }}
