# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: scheduler
spec:
  selector:
    app: scheduler
  ports:
    - name: http-metrics
      protocol: TCP
      port: {{ .Values.scheduler.ports.metricsPort }}
      targetPort: {{ .Values.scheduler.ports.metricsPort }}
  sessionAffinity: None
  type: ClusterIP