apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-pool-webhook
  namespace: gpu-pool
  labels:
    app: gpu-pool-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-pool-webhook
  template:
    metadata:
      labels:
        app: gpu-pool-webhook
    spec:
      serviceAccountName: gpu-pool-webhook
      containers:
      - name: webhook
        image: cr.makina.rocks/inho.kim/gpu-pool-webhook:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8443
          name: webhook-api
        env:
        - name: TLS_CERT_FILE
          value: /etc/certs/tls.crt
        - name: TLS_PRIVATE_KEY_FILE
          value: /etc/certs/tls.key
        - name: WEBHOOK_PORT
          value: "8443"
        volumeMounts:
        - name: webhook-certs
          mountPath: /etc/certs
          readOnly: true
        livenessProbe:
          httpGet:
            path: /health
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      volumes:
      - name: webhook-certs
        secret:
          secretName: gpu-pool-webhook-certs

---
apiVersion: v1
kind: Service
metadata:
  name: gpu-pool-webhook
  namespace: gpu-pool
  labels:
    app: gpu-pool-webhook
spec:
  ports:
  - name: webhook-api
    port: 443
    targetPort: 8443
  selector:
    app: gpu-pool-webhook

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpu-pool-webhook
  namespace: gpu-pool

---
apiVersion: v1
kind: Namespace
metadata:
  name: gpu-pool
