apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: gpu-pool-webhook
webhooks:
- name: gpu-pool.mrxrunway.ai
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR6VENDQXJXZ0F3SUJBZ0lVWEs5VitBWGFJMDIzUHJUdXdNVmFNMTNOb0c4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1JqRUxNQWtHQTFVRUJoTUNTMUl4RGpBTUJnTlZCQWdNQlZObGIzVnNNUkV3RHdZRFZRUUtEQWhIVUZVdApVRzl2YkRFVU1CSUdBMVVFQXd3TFozQjFMWEJ2YjJ3dFkyRXdIaGNOTWpVeE1ERTFNRFF5TmpFd1doY05Nall4Ck1ERTFNRFF5TmpFd1dqQllNUXN3Q1FZRFZRUUdFd0pMVWpFT01Bd0dBMVVFQ0F3RlUyVnZkV3d4RVRBUEJnTlYKQkFvTUNFZFFWUzFRYjI5c01TWXdKQVlEVlFRRERCMW5jSFV0Y0c5dmJDMTNaV0pvYjI5ckxtZHdkUzF3YjI5cwpMbk4yWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTWdtMDZ6LzluVHZ0QmFLCnBrNkZzU0VudWczbXVKdmsvQmJHdENwRStFYjBpTkZtajJyc2NBL3NEWkVac1NmVDc5Y3lsZWVLdjRUYTFOZEEKd2tNUlJ1enlCUndGMUhtVDFNcG9YUEtlaitwMjlpNjkvM0k2a2RwbTJKd3lzMmE3ZUxaOEN1L0Ziby9PbWl0RQprME01azFXK284NXdKbWJ6UWx2aHQ0R3V0WEpHclJnbFA0dmRTOTRiZlJOQ1piY25YNW80MFplVzhucWJXR2dOCnhBTnIzeFA3SmNrVGJJOWZreVlUUk1RQndrcG5JOERJcGhtVTRBNFpRcVAzMlBhckJJVXFkNlExanJOczFhVkMKQ3JlTXJFVnU1eVYxaHdPQjdZcS83dk5TTDdqU3RWQ1FXRG1iTHZCaUVlbmhaYytzSXRiUmp3R1hadnZFWldKcwpKUVpLUVVNQ0F3RUFBYU9Cb0RDQm5UQUpCZ05WSFJNRUFqQUFNQXNHQTFVZER3UUVBd0lGNERDQmdnWURWUjBSCkJIc3dlWUlRWjNCMUxYQnZiMnd0ZDJWaWFHOXZhNElaWjNCMUxYQnZiMnd0ZDJWaWFHOXZheTVuY0hVdGNHOXYKYklJZFozQjFMWEJ2YjJ3dGQyVmlhRzl2YXk1bmNIVXRjRzl2YkM1emRtT0NLMmR3ZFMxd2IyOXNMWGRsWW1odgpiMnN1WjNCMUxYQnZiMnd1YzNaakxtTnNkWE4wWlhJdWJHOWpZV3d3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCCkFKdHNaWWN2L2JTNW8zd20zUFF5bXNXWnJRekViZVkwMlE4ekNLRjVTa1U1RlVVWEJ3dXkyVys4dkllVU5kdW0KVGdzMEt3RVVkSjlRSmZVRTVnMGRhSGNNUEZMTlpTZlFWa045MTBneDA4bFVKZVhCNDBuQW83dnBkbFc1M09OQQpiUVVhQnBFZE5SSUF6dFNQM3lCUkR4UVRFQ2czNEYxeUFxVkVqdVhadmNPcFZ3bENNdXFiZnl4LzVoSlh4M0pQClRGZyszT0YzbUN3RExjYmNrQUQ4MnN3SU9jRUp2M0ZTUUdGb3lHbmhSYlp3RVZBQ3lIVXJJbzhwTjQ4VWR6dHEKZ0Z5dXYyRU5nZDhsM3ZrS2IvRnJ3TlB2VWVKU0k3aWFpNDBTRmtEOExray9tK0U0NGpCRTdDcGJxWmV5b1dsYwpiSE9oaUV3ZGFqb3pqWmsvYllFdi9BVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: gpu-pool-webhook
      namespace: gpu-pool
      path: "/mutate"
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  failurePolicy: Fail  # Webhook 실패 시에도 Pod 생성 허용
  namespaceSelector:
    matchExpressions:
    - key: name
      operator: NotIn
      values: ["kube-system", "gpu-pool"]  # 시스템 네임스페이스 제외
