apiVersion: v1
clusters:
- cluster:
    server: https://capsule-proxy.${DOMAIN_HOST}
    insecure-skip-tls-verify: true
  name: k3d-${CLUSTER_NAME}
contexts:
- context:
    cluster: k3d-${CLUSTER_NAME}
    namespace: ${TARGET_NAMESPACE}
    user: oidc-user
  name: k3d-${CLUSTER_NAME}
current-context: k3d-${CLUSTER_NAME}
kind: Config
preferences: {}
users:
- name: oidc-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: kubectl
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=${KUBERNETES__OIDC_ISSUER_URL}
      - --oidc-client-id=${KUBERNETES__OIDC_CLIENT_ID}
      - --insecure-skip-tls-verify
      interactiveMode: IfAvailable
