apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ${GROUP}-${ROLE}
  namespace: ${TARGET_NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ${ROLE}
subjects:
  - kind: Group
    name: "${GROUP}"
    apiGroup: rbac.authorization.k8s.io
