annotations:
  artifacthub.io/images: |
    - name: openmetadata-server
      image: docker.io/openmetadata/server:1.9.7
  artifacthub.io/license: Apache-2.0
  artifacthub.io/recommendations: |
    - name: bitnami/mysql
    - name: apache/airflow
    - name: opensearchproject/opensearch
  artifacthub.io/support: https://github.com/open-metadata/openmetadata-helm-charts/issues
  kubeVersion: '>=1.24'
apiVersion: v2
appVersion: 1.9.7
description: A Helm chart for OpenMetadata on Kubernetes
home: https://open-metadata.org/
icon: https://open-metadata.org/assets/favicon.png
keywords:
- metadata
- data-science
- data
- machine-learning
- automation
- big-data
- bigdata
- artificial-intelligence
- datascience
- data-engineering
- data-catalog
- metadata-api
- governance
- data-profiling
- metadata-management
- dataengineering
- dataquality
- bigdataanalytics
- datadiscovery
maintainers:
- email: support@open-metadata.org
  name: OpenMetadata
name: openmetadata
sources:
- https://github.com/open-metadata/OpenMetadata
- https://github.com/open-metadata/openmetadata-helm-charts
type: application
version: 1.9.7
