# Copyright 2025 NVIDIA CORPORATION
  # SPDX-License-Identifier: Apache-2.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kai-podgroup-controller
subjects:
  - kind: ServiceAccount
    name: podgroup-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: kai-podgroup-controller
  apiGroup: rbac.authorization.k8s.io
