# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kai-podgroup-controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - pods/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scheduling.run.ai
  resources:
  - podgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scheduling.run.ai
  resources:
  - podgroups/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
