apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capsule-resourcepoolclaim-provisioner
rules:
- apiGroups: ["capsule.clastix.io"]
  resources: ["resourcepoolclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
